### ISSUE TITLE
Arrumar CSS

### ISSUE THREAD

**Issue by pedrobolgheroni** [Obra-Go/ObraGoWebApp#4]
**Home**

- Logo está ruim, não dá pra ver.
- ícone arrumar cor, tamanho (grande em relação ao texto), espaço entre eles está ruim.
- Tira o produtos, coloca quem somos e dúvidas no footer.
- pensar o pq do menu está ali, oq ele vai mostrar

**Finalizar Compra**
- cor no número de quantidade 
- arrumar cores do carrinho
- cores do header e footer trabalham juntos e é bom ser as msm em todas páginas(a cor do home esta boa, mas dessa página não)
- o tamanho das letras está desproporcional, as letras estão pequenas e tem mt espaço.
- colocar endereço no finalizar compra.

Colocar olhinho no input da senha (para poder ver se a senha está certa )
Pode colocar o olhinho ou para confirmar senha

**Comment by JoaoGuiNovaes** [comment]
As imagens também tao toda cagada
